name: Check

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Run prettier
        uses: borales/actions-yarn@v4
        with:
          cmd: prettier
        if: always()

      - name: Run ESLint
        uses: borales/actions-yarn@v4
        with:
          cmd: lint
        if: always()
